name: GitHub Pages
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm start & npx wait-on http://localhost:3000
      env:
        CI: true
    #- name: Build
    #  run: npm run build:prod

    #- name: Deploy
    #  if: success()
    #  uses: solybum/hexo-deploy@master
    #  env:
    #    PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    PUBLISH_REPOSITORY: josmilla/josmilla.github.io # The repository the action should deploy to.
    #    BRANCH: master  # The branch the action should deploy to.
    #    PUBLISH_DIR: ./public # The folder the action should deploy.
